import {
  AnimalsSubcategories,
  CategoriesType,
  DevicesQualities,
  DevicesSubcategories,
  HealthItemsAdTypes,
  HealthItemsSubcategories,
  HouseholdSubcategories,
  JobsSubcategories,
  KeysSubcategories,
  PersonalItemsOfferTypes,
  PersonalItemsSubcategories,
  PersonalItemsTargets,
  RealEstateAddons,
  RealEstateCount,
  RealEstateOfferTypes,
  RealEstateSubcategories,
  ServiceSubcategories,
  SparePartsSubcategories,
  VehicleColor,
  VehicleCondition,
  VehicleFuelType,
  VehicleMileageMeasures,
  VehicleSubcategories,
  VehicleTransmissionType,
} from '@/src/enums/categories'
import { CategoriesSearch } from '@/src/types/structs/search'

const subcategories: CategoriesSearch = {
  [CategoriesType.Services]: {
    key: KeysSubcategories.Subcategory,
    array: [
      ServiceSubcategories.Transportation,
      ServiceSubcategories.Entertainment,
      ServiceSubcategories.Jurisprudence,
      ServiceSubcategories.Health,
      ServiceSubcategories.Household,
      ServiceSubcategories.Maintenance,
      ServiceSubcategories.Educational,
      ServiceSubcategories.Caregiving,
      ServiceSubcategories.Other,
    ],
    additional: [],
    checkAdditional: false,
  },
  [CategoriesType.Vehicle]: {
    key: KeysSubcategories.VehicleType,
    checkAdditional: true,
    array: [VehicleSubcategories.Car, VehicleSubcategories.Motorcycle, VehicleSubcategories.Other],
    additional: [
      {
        key: KeysSubcategories.OfferType,
        array: [RealEstateOfferTypes.Rent, RealEstateOfferTypes.Sell],
      },
      {
        key: KeysSubcategories.MileageMeasure,
        array: [VehicleMileageMeasures.Kilometer, VehicleMileageMeasures.Mile],
      },
      {
        key: KeysSubcategories.Condition,
        array: [VehicleCondition.VeryGood, VehicleCondition.Good, VehicleCondition.Normal, VehicleCondition.Bad],
      },
      {
        key: KeysSubcategories.TransmissionType,
        array: [VehicleTransmissionType.Manual, VehicleTransmissionType.Automatic],
      },
      {
        key: KeysSubcategories.FuelType,
        array: [
          VehicleFuelType.Gasoline,
          VehicleFuelType.Diesel,
          VehicleFuelType.Gas,
          VehicleFuelType.Electricity,
          VehicleFuelType.Hybrid,
          VehicleFuelType.Other,
        ],
      },
      {
        key: KeysSubcategories.Quality,
        array: [DevicesQualities.New, DevicesQualities.Used],
      },
      {
        key: KeysSubcategories.VehicleColor,
        array: [
          VehicleColor.Beige,
          VehicleColor.Blue,
          VehicleColor.Black,
          VehicleColor.Golden,
          VehicleColor.Brown,
          VehicleColor.Gray,
          VehicleColor.Green,
          VehicleColor.Orange,
          VehicleColor.Pink,
          VehicleColor.Purple,
          VehicleColor.Red,
          VehicleColor.Silver,
          VehicleColor.Vinous,
          VehicleColor.Violet,
          VehicleColor.White,
          VehicleColor.Yellow,
        ],
      },
    ],
  },
  [CategoriesType.RealEstate]: {
    key: KeysSubcategories.RealEstateType,
    array: [
      RealEstateSubcategories.Studio,
      RealEstateSubcategories.Apartment,
      RealEstateSubcategories.Townhouse,
      RealEstateSubcategories.House,
    ],
    checkAdditional: true,
    additional: [
      {
        key: KeysSubcategories.OfferType,
        array: [RealEstateOfferTypes.Rent, RealEstateOfferTypes.Sell],
      },
      {
        key: KeysSubcategories.BedroomsCount,
        array: [RealEstateCount.One, RealEstateCount.Two, RealEstateCount.ThreeAndMore],
      },
      {
        key: KeysSubcategories.BathsCount,
        array: [RealEstateCount.One, RealEstateCount.Two, RealEstateCount.ThreeAndMore],
      },
      {
        key: KeysSubcategories.Furniture,
        array: [RealEstateAddons.Furniture],
      },
      {
        key: KeysSubcategories.Pool,
        array: [RealEstateAddons.Pool],
      },
      {
        key: KeysSubcategories.Gym,
        array: [RealEstateAddons.Gym],
      },
    ],
  },
  [CategoriesType.Devices]: {
    key: KeysSubcategories.Subcategory,
    checkAdditional: false,
    array: [
      DevicesSubcategories.Phone,
      DevicesSubcategories.GameConsole,
      DevicesSubcategories.Photographic,
      DevicesSubcategories.AudioAndVideo,
      DevicesSubcategories.Computer,
      DevicesSubcategories.ComputerParts,
      DevicesSubcategories.Office,
      DevicesSubcategories.Other,
    ],
    additional: [{ key: KeysSubcategories.Quality, array: [DevicesQualities.New, DevicesQualities.Used] }],
  },
  [CategoriesType.Household]: {
    key: KeysSubcategories.Subcategory,
    array: [
      HouseholdSubcategories.Appliances,
      HouseholdSubcategories.Food,
      HouseholdSubcategories.Furniture,
      HouseholdSubcategories.BedSheets,
      HouseholdSubcategories.Repairing,
      HouseholdSubcategories.Kitchen,
      HouseholdSubcategories.Bathroom,
      HouseholdSubcategories.Bedroom,
      HouseholdSubcategories.Dishes,
      HouseholdSubcategories.Plants,
      HouseholdSubcategories.Tools,
      HouseholdSubcategories.Other,
    ],
    checkAdditional: false,
    additional: [{ key: KeysSubcategories.Quality, array: [DevicesQualities.New, DevicesQualities.Used] }],
  },
  [CategoriesType.Animals]: {
    key: KeysSubcategories.AdType,
    array: [AnimalsSubcategories.Goods, AnimalsSubcategories.Animals],
    checkAdditional: false,
    additional: [],
  },
  [CategoriesType.PersonalItems]: {
    key: KeysSubcategories.ItemType,
    array: [
      PersonalItemsSubcategories.Cloth,
      PersonalItemsSubcategories.Shoes,
      PersonalItemsSubcategories.Accessory,
      PersonalItemsSubcategories.Toy,
      PersonalItemsSubcategories.Sport,
      PersonalItemsSubcategories.Bicycle,
      PersonalItemsSubcategories.Other,
    ],
    checkAdditional: false,
    additional: [
      {
        key: KeysSubcategories.OfferType,
        array: [PersonalItemsOfferTypes.Sell, PersonalItemsOfferTypes.Gift, PersonalItemsOfferTypes.Rent],
      },
      { key: KeysSubcategories.Quality, array: [DevicesQualities.New, DevicesQualities.Used] },
      {
        key: KeysSubcategories.Target,
        array: [
          PersonalItemsTargets.Men,
          PersonalItemsTargets.Women,
          PersonalItemsTargets.Kids,
          PersonalItemsTargets.Everyone,
        ],
      },
    ],
  },
  [CategoriesType.Jobs]: {
    key: KeysSubcategories.AdType,
    array: [JobsSubcategories.Hiring, JobsSubcategories.Search],
    checkAdditional: false,
    additional: [],
  },
  [CategoriesType.HealthItems]: {
    key: KeysSubcategories.Subcategory,
    array: [
      HealthItemsSubcategories.BodyCare,
      HealthItemsSubcategories.DietarySupplements,
      HealthItemsSubcategories.Perfumery,
      HealthItemsSubcategories.Cosmetics,
      HealthItemsSubcategories.ForHair,
      HealthItemsSubcategories.Devices,
      HealthItemsSubcategories.Tools,
      HealthItemsSubcategories.Other,
    ],
    checkAdditional: false,
    additional: [
      {
        key: KeysSubcategories.AdType,
        array: [HealthItemsAdTypes.NewProduct, HealthItemsAdTypes.UsedProduct],
      },
    ],
  },
  [CategoriesType.SpareParts]: {
    key: KeysSubcategories.Subcategory,
    array: [
      SparePartsSubcategories.Parts,
      SparePartsSubcategories.Tires,
      SparePartsSubcategories.Chemical,
      SparePartsSubcategories.Tools,
      SparePartsSubcategories.Accessories,
      SparePartsSubcategories.Baggage,
      SparePartsSubcategories.MotorcycleEquipment,
      SparePartsSubcategories.AudioVideo,
      SparePartsSubcategories.Electronics,
      SparePartsSubcategories.Other,
    ],
    checkAdditional: false,
    additional: [{ key: KeysSubcategories.Quality, array: [DevicesQualities.New, DevicesQualities.Used] }],
  },
  [CategoriesType.Other]: { key: null, array: [], additional: [], checkAdditional: false },
  '': { key: KeysSubcategories.Subcategory, array: [], additional: [], checkAdditional: false },
}

export { subcategories }
