export enum CountriesType {
  Thailand = 'TH',
  Vietnam = 'VN',
  Indonesia = 'ID',
  Malaysia = 'MY',
  India = 'IN',
  Cambodia = 'KH',
  Laos = 'LA',
  UAE = 'AE',
  Turkey = 'TR',
  Georgia = 'GE',
  Armenia = 'AM',
  China = 'CN',
  Argentina = 'AR',
  Azerbaijan = 'AZ',
  Brazil = 'BR',
  Belarus = 'BY',
  Kazakhstan = 'KZ',
  Kyrgyzstan = 'KG',
  Turkmenistan = 'TM',
  Tajikistan = 'TJ',
  Uzbekistan = 'UZ',
}
